from sympy import *

x = symbols("x")

array_coef_for_polynom = []
array_coef_for_trig = []
array_coef_for_argument_trig = []
array_coef_for_exp = []
array_coef_for_logarifm = []
array_degree_for_variable_polynom = []
array_degree_for_trig = []
array_trig = []
array_exp = []
array_log = []
array_pow = []
array_line = []
array_coef_for_polynom1 = []
array_coef_for_trig1 = []
array_coef_for_argument_trig1 = []
array_coef_for_exp1 = []
array_coef_for_logarifm1 = []
array_degree_for_variable_polynom1 = []
array_degree_for_trig1 = []
array_trig1 = []
array_exp1 = []
array_log1 = []
array_pow1 = []
array_line1 = []
array_line_variable = []

