from method_introduction_under_dif_sign.arrays_for_introduction_under_dif_sign import *


# чистильщик листов/массовов
def cleaning_machine_for_introd_under_dif_sign():
    array_coef_for_polynom.clear()
    array_coef_for_trig.clear()
    array_coef_for_argument_trig.clear()
    array_coef_for_exp.clear()
    array_coef_for_logarifm.clear()
    array_degree_for_variable_polynom.clear()
    array_degree_for_trig.clear()
    array_trig.clear()
    array_exp.clear()
    array_log.clear()
    array_pow.clear()
    array_line.clear()
    array_coef_for_polynom1.clear()
    array_coef_for_trig1.clear()
    array_coef_for_argument_trig1.clear()
    array_coef_for_exp1.clear()
    array_coef_for_logarifm1.clear()
    array_degree_for_variable_polynom1.clear()
    array_degree_for_trig1.clear()
    array_trig1.clear()
    array_exp1.clear()
    array_log1.clear()
    array_pow1.clear()
    array_line1.clear()
    array_line_variable.clear()
