from method_only_integral_and_method_integral_of_piece_res.arrays_variable_and_symbols import *

def clearing_machine():
    array_constants.clear()
    array_coefficients_polynomial.clear()
    array_coefficients_polynom.clear()
    array_coefficients_trig.clear()
    array_coefficients_exp.clear()
    array_coefficients_trig_up.clear()
    array_coefficients_logarifm.clear()
    array_coefficients_power.clear()
    array_coefficients_for_argument_triganometrix.clear()
    array_coefficients_for_argument_exp.clear()
    array_coefficients_for_argument_triganometrix_up.clear()
    array_coefficients_for_argument_logarifm.clear()
    array_coefficients_for_argument_power.clear()
    array_trig.clear()
    array_trig_result.clear()
    array_exp.clear()
    array_exp_result.clear()
    array_logarifm.clear()
    array_logarifm_result.clear()
    array_power.clear()
    array_power_result.clear()
    array_degree_for_polyn.clear()
    array_degree_for_variable_polyn.clear()
    array_degree_polynomial.clear()
    array_degree_trig.clear()
    array_expression.clear()
    array_line_variable.clear()